[phases.setup]
nixPkgs = ["nodejs_20", "python310", "postgresql", "libpq"]

[phases.build]
cmds = [
    "cd root && python manage.py tailwind install && python manage.py tailwind build && python manage.py collectstatic --noinput"
]

[start]
cmd = "cd root && gunicorn root.wsgi:application --bind 0.0.0.0:$PORT"
