[build]
builder = "nixpacks"
buildCommand = "python manage.py tailwind install && python manage.py tailwind build && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd root && gunicorn root.wsgi:application --bind 0.0.0.0:$PORT"
