# Generated by Django 5.2.3 on 2025-06-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopThreeLeaderboard',
            new_name='TopLeaderboard',
        ),
    ]
