# Generated by Django 5.2.3 on 2025-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_rename_topthreeleaderboard_topleaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorsLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('points', models.IntegerField()),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='topleaderboard',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
