# Generated by Django 5.2.3 on 2025-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_constructorsleaderboard_alter_topleaderboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorsleaderboard',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topleaderboard',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
