# Generated by Django 5.2.3 on 2025-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_constructorsleaderboard_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('country_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('previous', 'Previous'), ('next', 'Next'), ('upcoming', 'Upcoming')], max_length=10)),
            ],
            options={
                'ordering': ['from_date'],
            },
        ),
        migrations.AlterField(
            model_name='constructorsleaderboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topleaderboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
