# Generated by Django 5.2.3 on 2025-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_calendar_alter_constructorsleaderboard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='to_date',
            field=models.DateField(),
        ),
    ]
