# Generated by Django 5.2.3 on 2025-06-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_calendar_from_date_alter_calendar_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
