# Generated by Django 5.2.3 on 2025-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_alter_calendar_from_date_alter_calendar_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('previous', 'Previous'), ('next', 'Next'), ('upcoming', 'Upcoming')], max_length=10),
        ),
    ]
