# Generated by Django 5.2.3 on 2025-06-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0008_alter_calendar_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('flair', models.CharField(choices=[('news', 'News'), ('question', 'Question'), ('meme', 'Meme'), ('analysis', 'Analysis'), ('prediction', 'Prediction'), ('discussion', 'Discussion'), ('race_reaction', 'Race Reaction'), ('qualifying', 'Qualifying'), ('practice', 'Practice'), ('strategy', 'Strategy'), ('technical', 'Technical'), ('penalty', 'Penalty'), ('fantasy', 'F1 Fantasy'), ('fan_art', 'Fan Art'), ('highlight', 'Highlight'), ('throwback', 'Throwback'), ('driver_ranking', 'Driver Ranking'), ('poll', 'Poll'), ('rumor', 'Rumor'), ('announcement', 'Announcement')], max_length=25)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
