# Generated by Django 5.2.3 on 2025-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_post',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
