# Generated by Django 5.2.3 on 2025-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0014_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/image/default.jpg', upload_to='images/'),
        ),
    ]
