# Generated by Django 5.2.3 on 2025-07-04 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0016_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
