# Generated by Django 5.2.3 on 2025-07-17 05:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0017_alter_chat_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topleaderboard',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
