# Generated by Django 5.2.3 on 2025-07-17 07:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0019_alter_calendar_image_alter_chat_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='country_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
