# Generated by Django 5.2.3 on 2025-07-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0020_alter_calendar_country_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('status', models.CharField(default='Finished', max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.calendar')),
            ],
            options={
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(related_name='races', through='garage.RaceResult', to='garage.driver'),
        ),
    ]
