# Generated by Django 5.2.3 on 2025-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0021_driver_raceresult_calendar_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
